spring.application.name: Data Generator
logging.level.org.springframework: ERROR
logging.level.org.apache.parquet.hadoop: WARN
spring.datasource:
  url: jdbc:postgresql://localhost:5432/shop_data
  username: postgres
  password: 1qaz2wsXX
  driver-class-name: org.postgresql.Driver


spring:
  profiles.active: local
  jpa:
    properties:
      hibernate:
        ejb:
          classloaders: org.springframework.instrument.classloading.InstrumentationLoadTimeWeaver
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: true
datasource:
  app:
    platform: postgres
    driver-class-name: org.postgresql.Driver

server.port: 8095

spark:
  postgres:
    url: jdbc:postgresql://172.30.0.4:5432/shop_data
    user: postgres
    password: "1qaz2wsXX"
    localPath: /mnt/spark
    jars:
      - ./jars/postgresql-42.6.0.jar
    master: spark://localhost:7077
    maxExecutors: 1
    coresPerExecutor: 1
    memory: 6g
    port: 9042
    servers: dpl-dev-host
    retryWait: 3
    maxRetries: 3

