# Please note we are using Docker Compose version 3
version: '3'
services:
  db:
    image: postgres:11
    restart: always
    container_name: pg11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_PASSWORD: 1qaz2wsXX
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    restart: always
    volumes:
      - ./redis:/usr/local/etc/redis
    ports:
      - "6379:6379"

  spark-master:
    image: bde2020/spark-master:2.3.1-hadoop2.7
    container_name: spark-master
    network_mode: host
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==softkit_maser_spark"

  spark-worker-1:
    image: bde2020/spark-worker:2.3.1-hadoop2.7
    container_name: spark-worker-1
    network_mode: host
    restart: always
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://softkit1:7077"
      - "constraint:node==softkit_maser_spark"

volumes:
  data01:
    driver: local

networks:
  dc1ring:
  data:
  elastic:
    driver: bridge


